M48
; DRILL file {KiCad 7.0.8} date 2024 June 06, Thursday 18:22:48
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-06T18:22:48-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.9567Y-2.4213
X3.9567Y-4.5866
X7.0669Y-2.4213
X7.0669Y-4.5866
T0
M30
